-- 2 VERIFICAR DEPENDENCIAS

SELECT NAME, TYPE, REFERENCED_NAME 
FROM USER_DEPENDENCIES 
WHERE REFERENCED_NAME = 'EMPLOYEES';

CREATE VIEW v_lista_empleados AS SELECT last_name, salary FROM EMPLOYEES;
CREATE VIEW v_lista_empleados2 AS SELECT first_name, salary FROM EMPLOYEES;

-- 3 DEPENDENCIAS DIRECTAS 

CREATE TABLE LOCALIDADES AS SELECT * FROM LOCATIONS;

SELECT * FROM LOCALIDADES;

CREATE VIEW JAPON AS SELECT * FROM LOCALIDADES WHERE 
COUNTRY_ID ='JP';

ALTER VIEW JAPON COMPILE;

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME = 'JAPON';

ALTER TABLE LOCALIDADES MODIFY CITY VARCHAR2(100);


-- 4 DEPENDENCIAS INDIRECTAS 

CREATE OR REPLACE FUNCTION NUM_JAPON 
RETURN NUMBER 
IS 
	X NUMBER;
BEGIN 
	SELECT COUNT(*) INTO X FROM JAPON;
	RETURN X;
END;



SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME ='NUM_JAPON';

ALTER TABLE LOCALIDADES MODIFY CITY VARCHAR2(50);

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%JAPON%';

ALTER FUNCTION NUM_JAPON COMPILE;


/*SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('LOCALIDADES', 'JAPON', 'NUM_JAPON');*/

SELECT OBJECT_TYPE, COUNT(*) FROM DBA_OBJECTS WHERE
STATUS = 'INVALID' GROUP BY OBJECT_TYPE;



-- CURSORES VARIABLES

DECLARE

	TYPE CURSOR_VARIABLE IS REF CURSOR;
	V1 CURSOR_VARIABLE;
	X1 CURSOR_VARIABLE;

	EMPLEADOS EMPLOYEES%ROWTYPE;
	DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN 
	
	OPEN V1 FOR SELECT * FROM EMPLOYEES;
	FETCH V1 INTO EMPLEADOS;
	DBMS_OUTPUT.PUT_LINE(EMPLEADOS.SALARY);
	CLOSE V1;
	
	OPEN V1 FOR SELECT * FROM DEPARTMENTS;
	FETCH V1 INTO DEPARTAMENTOS;
	DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
	CLOSE V1;
	
	OPEN V1 FOR SELECT * FROM DEPARTMENTS;
	FETCH V1 INTO DEPARTAMENTOS;
	DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
	CLOSE V1;
	
END;

SELECT * FROM EMPLOYEES;
SELECT * FROM departments;


-- BUCLES CON CURSORES VARIABLES


-- REF CURSORS y Tipos


DECLARE 
	TYPE C1 IS REF CURSOR RETURN DEPARTMENTS%ROWTYPE;
	V1 C1;
	DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN	
	OPEN V1 FOR SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID > 150;
	FETCH V1 INTO DEPARTAMENTOS;
	WHILE V1%FOUND LOOP
		DBMS_OUTṔUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
		FETCH V1 INTO DEPARTAMENTOS;
	END LOOP;
	CLOSE V1;
END;



